import { Heroe } from "./heroe";

export const HEROES: Heroe[] = [
  {
    nombre: 'Aquaman',
    bio: 'El poder más reconocido de Aquaman es la capacidad telepática para comunicarse con la vida marina, la cual puede convocar a grandes distancias.',
    img: 'assets/img/aquaman.png',
    aparicion: '1941-11-01',
    casa: 'DC',
  },
  {
    nombre: 'Batman',
    bio: 'Los rasgos principales de Batman se resumen en «destreza física, habilidades deductivas y obsesión». La mayor parte de las características básicas de los cómics han variado por las diferentes interpretaciones que le han dado al personaje.',
    img: 'assets/img/batman.png',
    aparicion: '1939-05-01',
    casa: 'DC',
  },
  {
    nombre: 'Daredevil',
    bio: 'Al haber perdido la vista, los cuatro sentidos restantes de Daredevil fueron aumentados por la radiación a niveles superhumanos, en el accidente que tuvo cuando era niño. A pesar de su ceguera, puede "ver" a través de un "sexto sentido" que le sirve como un radar similar al de los murciélagos.',
    img: 'assets/img/daredevil.png',
    aparicion: '1964-01-01',
    casa: 'Marvel',
  },
  {
    nombre: 'Hulk',
    bio: 'Su principal poder es su capacidad de aumentar su fuerza hasta niveles prácticamente ilimitados a la vez que aumenta su furia. Dependiendo de qué personalidad de Hulk esté al mando en ese momento (el Hulk Banner es el más débil, pero lo compensa con su inteligencia).',
    img: 'assets/img/hulk.png',
    aparicion: '1962-05-01',
    casa: 'Marvel',
  },
  {
    nombre: 'Linterna Verde',
    bio: 'Poseedor del anillo de poder que posee la capacidad de crear manifestaciones de luz sólida mediante la utilización del pensamiento. Es alimentado por la Llama Verde (revisada por escritores posteriores como un poder místico llamado Starheart), una llama mágica contenida en dentro de un orbe (el orbe era en realidad un meteorito verde de metal que cayó a la Tierra, el cual encontró un fabricante de lámparas llamado Chang)',
    img: 'assets/img/linterna-verde.png',
    aparicion: '1940-06-01',
    casa: 'DC',
  },
  {
    nombre: 'Spider-Man',
    bio: 'Tras ser mordido por una araña radiactiva, obtuvo los siguientes poderes sobrehumanos, una gran fuerza, agilidad, poder trepar por paredes. La fuerza de Spider-Man le permite levantar 10 toneladas o más. Gracias a esta gran fuerza Spider-Man puede realizar saltos íncreibles. Un "sentido arácnido", que le permite saber si un peligro se cierne sobre él, antes de que suceda. En ocasiones este puede llevar a Spider-Man al origen del peligro.',
    img: 'assets/img/spiderman.png',
    aparicion: '1962-08-01',
    casa: 'Marvel',
  },
  {
    nombre: 'Wolverine',
    bio: 'En el universo ficticio de Marvel, Wolverine posee poderes regenerativos que pueden curar cualquier herida, por mortal que ésta sea, además ese mismo poder hace que sea inmune a cualquier enfermedad existente en la Tierra y algunas extraterrestres . Posee también una fuerza sobrehumana, que si bien no se compara con la de otros superhéroes como Hulk, sí sobrepasa la de cualquier humano.',
    img: 'assets/img/wolverine.png',
    aparicion: '1974-11-01',
    casa: 'Marvel',
  },
  {
    nombre: 'Superman',
    bio: 'Durante la mayor parte de su existencia, el famoso arsenal de poderes de Superman ha incluido vuelo, superfuerza, invulnerabilidad, supervelocidad, poderes de visión (rayos x, calorífica, telescópica, infrarroja, y microscópica), superoído, y superaliento, el cual le permite soplar a temperaturas congelantes así como ejercer la fuerza de un viento huracanado.',
    img: 'assets/img/superman.jpg',
    aparicion: '1938-04-01',
    casa: 'DC',
  },
  {
    nombre: 'Ironman',
    bio: 'Anthony Edward Stark, conocido como Tony Stark, es un multimillonario magnate empresarial estadounidense, playboy e ingenioso científico, quien sufrió una grave lesión en el pecho durante un secuestro en el Medio Oriente. Cuando sus captores intentan forzarlo a construir un arma de destrucción masiva crea, en cambio, una armadura para salvar su vida y escapar del cautiverio. Más tarde, Stark desarrolla su traje, agregando armas y otros dispositivos tecnológicos que diseñó a través de su compañía, Industrias Stark. Él usa el traje y las versiones sucesivas para proteger al mundo como Iron Man. Aunque al principio ocultó su verdadera identidad, Stark finalmente declaró que era Iron Man en un anuncio público.',
    img: 'assets/img/ironman.jpg',
    aparicion: '1963-03-01',
    casa: 'Marvel',
  },
  {
    nombre: 'Wonderwoman',
    bio: 'En su tierra natal es conocida como la princesa Diana de Temiscira pero fuera de esta utiliza la identidad secreta de Diana Prince. Está dotada de una amplia gama de poderes superhumanos y habilidades de combate de batalla superiores, gracias a sus dones obtenidos de los dioses y su amplio entrenamiento. Ella posee un gran arsenal de armas, incluyendo entre las principales el Lazo de la Verdad, un par de brazaletes mágicos indestructibles, su tiara, que sirve como arma, y en algunos relatos, en la edad de oro, tuvo un avión invisible. Pero más adelante, se le fue mostrando con la capacidad de volar cada vez con mayor frecuencia por lo que el avión invisible fue dejando de utilizarse.',
    img: 'assets/img/wonderwoman.jpg',
    aparicion: '1941-12-01',
    casa: 'DC',
  },
  {
    nombre: 'Flash',
    bio: 'Apodado el "Corredor Escarlata", todas las encarnaciones del Flash poseen "súper velocidad", que incluye la capacidad de correr, moverse y pensar extremadamente rápido, también puede atravesar la materia sólida, usar reflejos sobrehumanos y aparentemente violar ciertas leyes de la física, como superar la velocidad de la luz.',
    img: 'assets/img/flash.png',
    aparicion: '1940-01-01',
    casa: 'DC',
  },
  {
    nombre: 'Deadpool',
    bio: 'El poder primario de Deadpool es un factor acelerado de curación, la velocidad de su factor de curación depende de la gravedad de la herida y del estado mental de Deadpool. Funciona más eficientemente cuando está despierto, alerta y de buen ánimo.',
    img: 'assets/img/deadpool.jpg',
    aparicion: '1991-02-01',
    casa: 'Marvel',
  },
  {
    nombre: 'Bestia',
    bio: 'Bestia era un mutante que poseía fuerza y agilidad sobrehumanas, con manos y pies de gran tamaño, aunque por lo demás parecía ser un humano normal.',
    img: 'assets/img/bestia.png',
    aparicion: '1963-01-01',
    casa: 'Marvel',
  },
];